image: ubuntu:16.10

pipelines:
  default:
    - step:
        script:
          - apt-get -y update
          - apt-get -y install cmake g++ libzip-dev
          - cmake . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic"
          - make
          - make test